name: ArmedArmorStands
main: me.phil14052.ArmedArmorStands.ArmedArmorStands
version: 1.2.3
author: phil14052 aka PhilPlays
api-version: 1.16
description: This plugins add so when you spawn a armor stand it spawns with arms
commands:
  armedarmorstands:
    description: ArmedArmorStands Main command
    aliases: [aas, armedarmorstand]
  togglearms:
    description: Toggle arms on Armor Stands