name: ArmedArmorStands
main: me.phil14052.ArmedArmorStands.ArmedArmorStands
version: 1.2.1
author: phil14052 aka PhilPlays
description: This plugins add so when you spawn a armor stand it spawns with arms
commands:
  armedarmorstands:
    description: ArmedArmorStands Main command
    aliases: [aas, armedarmorstands]
  togglearms:
    description: Toggle arms on Armor Stands